export const majorArcanaArtworkMap = {
  愚者: '/cards/rws/major-fool.png',
  魔术师: '/cards/rws/major-magician.png',
  女祭司: '/cards/rws/major-high-priestess.png',
  女皇: '/cards/rws/major-empress.png',
  皇帝: '/cards/rws/major-emperor.png',
  教皇: '/cards/rws/major-hierophant.png',
  恋人: '/cards/rws/major-lovers.png',
  战车: '/cards/rws/major-chariot.png',
  力量: '/cards/rws/major-strength.png',
  隐者: '/cards/rws/major-hermit.png',
  命运之轮: '/cards/rws/major-wheel-of-fortune.png',
  正义: '/cards/rws/major-justice.png',
  倒吊人: '/cards/rws/major-hanged-man.png',
  死神: '/cards/rws/major-death.png',
  节制: '/cards/rws/major-temperance.png',
  恶魔: '/cards/rws/major-devil.png',
  高塔: '/cards/rws/major-tower.png',
  星星: '/cards/rws/major-star.png',
  月亮: '/cards/rws/major-moon.png',
  太阳: '/cards/rws/major-sun.png',
  审判: '/cards/rws/major-judgement.png',
  世界: '/cards/rws/major-world.png',
};

export const minorArcanaArtworkMap = {
  权杖王牌: '/cards/rws/wands-ace.png',
  权杖二: '/cards/rws/wands-2.png',
  权杖三: '/cards/rws/wands-3.png',
  权杖四: '/cards/rws/wands-4.png',
  权杖五: '/cards/rws/wands-5.png',
  权杖六: '/cards/rws/wands-6.png',
  权杖七: '/cards/rws/wands-7.png',
  权杖八: '/cards/rws/wands-8.png',
  权杖九: '/cards/rws/wands-9.png',
  权杖十: '/cards/rws/wands-10.png',
  权杖侍者: '/cards/rws/wands-page.png',
  权杖骑士: '/cards/rws/wands-knight.png',
  权杖皇后: '/cards/rws/wands-queen.png',
  权杖国王: '/cards/rws/wands-king.png',

  圣杯王牌: '/cards/rws/cups-ace.png',
  圣杯二: '/cards/rws/cups-2.png',
  圣杯三: '/cards/rws/cups-3.png',
  圣杯四: '/cards/rws/cups-4.png',
  圣杯五: '/cards/rws/cups-5.png',
  圣杯六: '/cards/rws/cups-6.png',
  圣杯七: '/cards/rws/cups-7.png',
  圣杯八: '/cards/rws/cups-8.png',
  圣杯九: '/cards/rws/cups-9.png',
  圣杯十: '/cards/rws/cups-10.png',
  圣杯侍者: '/cards/rws/cups-page.png',
  圣杯骑士: '/cards/rws/cups-knight.png',
  圣杯皇后: '/cards/rws/cups-queen.png',
  圣杯国王: '/cards/rws/cups-king.png',

  宝剑王牌: '/cards/rws/swords-ace.png',
  宝剑二: '/cards/rws/swords-2.png',
  宝剑三: '/cards/rws/swords-3.png',
  宝剑四: '/cards/rws/swords-4.png',
  宝剑五: '/cards/rws/swords-5.png',
  宝剑六: '/cards/rws/swords-6.png',
  宝剑七: '/cards/rws/swords-7.png',
  宝剑八: '/cards/rws/swords-8.png',
  宝剑九: '/cards/rws/swords-9.png',
  宝剑十: '/cards/rws/swords-10.png',
  宝剑侍者: '/cards/rws/swords-page.png',
  宝剑骑士: '/cards/rws/swords-knight.png',
  宝剑皇后: '/cards/rws/swords-queen.png',
  宝剑国王: '/cards/rws/swords-king.png',

  星币王牌: '/cards/rws/pentacles-ace.png',
  星币二: '/cards/rws/pentacles-2.png',
  星币三: '/cards/rws/pentacles-3.png',
  星币四: '/cards/rws/pentacles-4.png',
  星币五: '/cards/rws/pentacles-5.png',
  星币六: '/cards/rws/pentacles-6.png',
  星币七: '/cards/rws/pentacles-7.png',
  星币八: '/cards/rws/pentacles-8.png',
  星币九: '/cards/rws/pentacles-9.png',
  星币十: '/cards/rws/pentacles-10.png',
  星币侍者: '/cards/rws/pentacles-page.png',
  星币骑士: '/cards/rws/pentacles-knight.png',
  星币皇后: '/cards/rws/pentacles-queen.png',
  星币国王: '/cards/rws/pentacles-king.png',
};

const artworkMap = {
  ...majorArcanaArtworkMap,
  ...minorArcanaArtworkMap,
};

export function getCardArtwork(card) {
  if (!card?.name) return null;
  return artworkMap[card.name] || null;
}
