function buildLocale(name, suit, locale) {
  return {
    name,
    keywords: locale.keywords,
    daily_upright: locale.dailyU,
    daily_reversed: locale.dailyR,
    reading_upright: locale.upright,
    reading_reversed: locale.reversed,
    detail: `${locale.intro}\n\n${locale.upright}\n\n${locale.reversed}\n\n${locale.lesson}`,
  };
}

function buildCard(card) {
  const zh = buildLocale(card.name_cn, card.suit, card.zh);
  return {
    id: card.id,
    number: card.number,
    name_cn: card.name_cn,
    name_en: card.name_en,
    arcana: 'minor',
    suit: card.suit,
    keywords: zh.keywords,
    daily_upright: zh.daily_upright,
    daily_reversed: zh.daily_reversed,
    reading_upright: zh.reading_upright,
    reading_reversed: zh.reading_reversed,
    detail: zh.detail,
    translations: {
      en: buildLocale(card.name_en, card.suit, card.en),
      it: buildLocale(card.name_it, card.suit, card.it),
    },
  };
}

const swords = [
  {
    id: 'ace-of-swords', number: 1, name_cn: '宝剑首牌', name_en: 'Ace of Swords', name_it: 'Asso di Spade', suit: 'swords',
    zh: { keywords: ['真相', '清晰', '突破', '决断', '新思想', '沟通'], dailyU: '今天适合说清事实、作出决定。一个新的想法可能切开混乱，让你看见真正的问题。', dailyR: '今天要小心判断混乱、沟通失真或用锋利语言伤人。先确认事实，再表达立场。', upright: '宝剑首牌正位代表真相显现、思路清晰与理性的突破。你正在获得切开迷雾、明确目标并开始行动的判断力。', reversed: '宝剑首牌逆位代表思维混乱、错误信息、沟通受阻或把聪明变成攻击。此时不宜凭片面证据仓促裁决。', intro: '宝剑首牌是风元素最初的锋芒，象征思想、语言和真相开始形成明确方向。剑能切开迷雾，也要求持剑者为判断负责。', lesson: '它的核心信息是：清晰本身是一种力量，但真正有价值的真相需要准确、诚实与克制。' },
    en: { keywords: ['truth', 'clarity', 'breakthrough', 'decision', 'new idea', 'communication'], dailyU: 'Speak clearly and decide from facts today. A new idea can cut through confusion.', dailyR: 'Watch for confused judgment, misinformation, or cutting words. Verify facts before taking a position.', upright: 'The Ace of Swords upright represents truth, clarity, and an intellectual breakthrough. You can define the issue and act with sharper judgment.', reversed: 'Reversed, it represents confusion, false information, blocked communication, or intelligence used as a weapon. Avoid premature conclusions.', intro: 'The Ace of Swords is the first edge of Air: thought, language, and truth taking a definite direction. The blade clears fog but demands responsibility.', lesson: 'Its lesson is that clarity is power, and useful truth requires accuracy, honesty, and restraint.' },
    it: { keywords: ['verita', 'chiarezza', 'svolta', 'decisione', 'nuova idea', 'comunicazione'], dailyU: 'Oggi parla con chiarezza e decidi sui fatti. Una nuova idea puo tagliare la confusione.', dailyR: 'Attenzione a giudizi confusi, informazioni false o parole taglienti. Verifica i fatti prima di prendere posizione.', upright: 'L’Asso di Spade diritto rappresenta verita, chiarezza e svolta mentale. Puoi definire il problema e agire con giudizio piu netto.', reversed: 'Rovesciato, indica confusione, informazioni errate, comunicazione bloccata o intelligenza usata come arma. Evita conclusioni premature.', intro: 'L’Asso di Spade e il primo filo dell’Aria: pensiero, linguaggio e verita prendono una direzione precisa. La lama dissolve la nebbia ma richiede responsabilita.', lesson: 'La lezione e che la chiarezza e potere, e una verita utile richiede precisione, onesta e misura.' },
  },
  {
    id: 'two-of-swords', number: 2, name_cn: '宝剑二', name_en: 'Two of Swords', name_it: 'Due di Spade', suit: 'swords',
    zh: { keywords: ['僵局', '选择', '防御', '回避', '平衡', '信息不足'], dailyU: '今天适合暂停外界噪音，冷静比较两个方向。暂缓决定可以，但要继续收集信息。', dailyR: '今天要小心逃避选择或被矛盾压垮。拖延不会让问题消失，先承认自己真正害怕什么。', upright: '宝剑二正位代表僵局、谨慎权衡与暂时封闭感受。你可能尚未掌握全部信息，因此不愿轻易选择。', reversed: '宝剑二逆位代表犹豫失控、真相突破防线或长期回避终于无法维持。你需要取下眼罩，接受选择必然带来的代价。', intro: '宝剑二中的人物蒙住双眼，双剑交叉，表现理性与情感互相牵制的静止状态。', lesson: '它提醒你：暂停是为了获得清晰，不是为了永久逃离决定。' },
    en: { keywords: ['stalemate', 'choice', 'defense', 'avoidance', 'balance', 'limited information'], dailyU: 'Quiet outside noise and compare two paths. Delay can be useful if you keep gathering information.', dailyR: 'Avoid being paralyzed by choice. Delay will not erase the issue; name what you fear.', upright: 'The Two of Swords upright represents stalemate, careful weighing, and emotional defense. You may lack enough information to choose.', reversed: 'Reversed, indecision becomes unsustainable or truth breaks through the defense. Remove the blindfold and accept the cost of choosing.', intro: 'The blindfolded figure and crossed blades show reason and feeling holding each other in suspension.', lesson: 'Pause should create clarity, not become permanent avoidance.' },
    it: { keywords: ['stallo', 'scelta', 'difesa', 'evitamento', 'equilibrio', 'informazioni limitate'], dailyU: 'Riduci il rumore esterno e confronta due strade. Rimandare aiuta solo se continui a raccogliere informazioni.', dailyR: 'Non lasciarti paralizzare dalla scelta. Il rinvio non cancella il problema: riconosci cio che temi.', upright: 'Il Due di Spade diritto rappresenta stallo, valutazione prudente e difesa emotiva. Potrebbero mancare informazioni sufficienti.', reversed: 'Rovesciato, l’indecisione non e piu sostenibile o la verita supera la difesa. Togli la benda e accetta il costo della scelta.', intro: 'La figura bendata e le lame incrociate mostrano ragione e sentimento sospesi l’uno contro l’altro.', lesson: 'La pausa deve creare chiarezza, non diventare evitamento permanente.' },
  },
  {
    id: 'three-of-swords', number: 3, name_cn: '宝剑三', name_en: 'Three of Swords', name_it: 'Tre di Spade', suit: 'swords',
    zh: { keywords: ['心碎', '悲伤', '分离', '真相', '失望', '疗愈'], dailyU: '今天可能面对令人难过的事实。允许情绪经过，不必假装坚强，诚实是疗愈的起点。', dailyR: '今天适合释放旧伤，但要避免反复刺痛自己。原谅不等于否认，而是停止让伤口控制现在。', upright: '宝剑三正位代表心碎、失望、分离与不可回避的痛苦真相。看见伤口虽然艰难，却让真正的疗愈成为可能。', reversed: '宝剑三逆位代表恢复、释放悲伤，或旧伤仍被压抑并反复影响关系。你需要给痛苦一个被理解的位置。', intro: '三把剑刺入心脏，是塔罗中最直接的悲伤图像。它说明思想、话语或事实也能造成真实的情感伤害。', lesson: '它的核心不是永远停在心碎，而是让真相穿过之后，慢慢把心还给自己。' },
    en: { keywords: ['heartbreak', 'grief', 'separation', 'truth', 'disappointment', 'healing'], dailyU: 'A painful truth may surface. Let emotion move through you; honesty begins healing.', dailyR: 'Release an old wound without reopening it repeatedly. Forgiveness means the wound no longer rules the present.', upright: 'The Three of Swords upright represents heartbreak, disappointment, separation, and painful truth. Seeing the wound makes genuine healing possible.', reversed: 'Reversed, it represents recovery and release, or an old wound still suppressed and shaping relationships.', intro: 'Three blades pierce a heart, showing how thoughts, words, and facts can cause real emotional injury.', lesson: 'The card does not ask you to live in heartbreak, but to reclaim your heart after truth passes through.' },
    it: { keywords: ['cuore spezzato', 'dolore', 'separazione', 'verita', 'delusione', 'guarigione'], dailyU: 'Puo emergere una verita dolorosa. Lascia passare l’emozione: l’onesta avvia la guarigione.', dailyR: 'Libera una vecchia ferita senza riaprirla continuamente. Perdonare significa non lasciarle governare il presente.', upright: 'Il Tre di Spade diritto rappresenta cuore spezzato, delusione, separazione e verita dolorosa. Vedere la ferita rende possibile guarire.', reversed: 'Rovesciato, indica recupero e rilascio, oppure una vecchia ferita ancora repressa che influenza i rapporti.', intro: 'Tre lame attraversano un cuore, mostrando che pensieri, parole e fatti possono produrre vere ferite emotive.', lesson: 'La carta non chiede di vivere nel dolore, ma di riprenderti il cuore dopo che la verita lo ha attraversato.' },
  },
  {
    id: 'four-of-swords', number: 4, name_cn: '宝剑四', name_en: 'Four of Swords', name_it: 'Quattro di Spade', suit: 'swords',
    zh: { keywords: ['休息', '恢复', '暂停', '沉思', '退场', '疗养'], dailyU: '今天适合减少刺激、休息和整理思绪。暂时退后不是懒惰，而是在恢复继续前进的力量。', dailyR: '今天要小心休息不足、精神过载，或停太久而更加焦虑。身体已经在提醒你调整节奏。', upright: '宝剑四正位代表休息、恢复与主动暂停。经历紧张之后，你需要让神经和思想真正安静下来。', reversed: '宝剑四逆位代表疲惫累积、无法放松、过早复出，或从长期停顿中重新苏醒。恢复不能只靠意志催促。', intro: '宝剑四把风元素的活动暂时收起，让思想进入安静的修复空间。', lesson: '它提醒你：休息不是浪费时间，而是维持清醒与行动能力的一部分。' },
    en: { keywords: ['rest', 'recovery', 'pause', 'reflection', 'retreat', 'recuperation'], dailyU: 'Reduce stimulation, rest, and organize your thoughts. Stepping back restores your ability to continue.', dailyR: 'Watch for sleep debt, mental overload, or anxiety from pausing too long. Adjust your pace.', upright: 'The Four of Swords upright represents rest, recovery, and deliberate pause. After strain, your mind and nervous system need quiet.', reversed: 'Reversed, it represents accumulated exhaustion, inability to relax, returning too early, or awakening after a long pause.', intro: 'The Four of Swords temporarily stills the activity of Air so the mind can repair.', lesson: 'Rest is not wasted time; it preserves clarity and the capacity to act.' },
    it: { keywords: ['riposo', 'recupero', 'pausa', 'riflessione', 'ritiro', 'convalescenza'], dailyU: 'Riduci gli stimoli, riposa e ordina i pensieri. Fare un passo indietro ripristina la capacita di continuare.', dailyR: 'Attenzione a mancanza di sonno, sovraccarico mentale o ansia per una pausa troppo lunga. Regola il ritmo.', upright: 'Il Quattro di Spade diritto rappresenta riposo, recupero e pausa consapevole. Dopo la tensione, mente e sistema nervoso hanno bisogno di silenzio.', reversed: 'Rovesciato, indica stanchezza accumulata, incapacita di rilassarsi, ritorno prematuro o risveglio dopo una lunga pausa.', intro: 'Il Quattro di Spade calma temporaneamente l’attivita dell’Aria affinche la mente possa ripararsi.', lesson: 'Il riposo non e tempo perso: conserva chiarezza e capacita di agire.' },
  },
  {
    id: 'five-of-swords', number: 5, name_cn: '宝剑五', name_en: 'Five of Swords', name_it: 'Cinque di Spade', suit: 'swords',
    zh: { keywords: ['冲突', '胜负', '代价', '争执', '自私', '空洞胜利'], dailyU: '今天要留意为了赢而破坏关系。说服别人不等于解决问题，先判断这场争斗是否值得。', dailyR: '今天适合停止无意义的对抗、道歉或退出消耗。放下胜负心，才能真正结束冲突。', upright: '宝剑五正位代表冲突、权力较量与代价高昂的胜利。即使你在表面上赢了，也可能失去信任、合作或内在平静。', reversed: '宝剑五逆位代表和解、后悔、冲突余波，或暗中的敌意仍未解决。结束战争需要承担自己造成的影响。', intro: '宝剑五描绘胜者收起刀剑，而其他人失落离开，提醒人关注胜利之后留下了什么。', lesson: '它的核心问题是：如果必须失去最重要的东西才能赢，这还算胜利吗？' },
    en: { keywords: ['conflict', 'winning', 'cost', 'argument', 'self-interest', 'empty victory'], dailyU: 'Do not damage a relationship merely to win. Persuasion is not resolution; decide whether this battle matters.', dailyR: 'End pointless opposition, apologize, or leave a draining fight. Releasing the need to win ends conflict.', upright: 'The Five of Swords upright represents conflict, power struggle, and costly victory. Winning outwardly may cost trust, cooperation, or peace.', reversed: 'Reversed, it represents reconciliation, regret, aftermath, or hostility still hidden. Ending war requires owning your impact.', intro: 'The victor gathers swords while others walk away, directing attention to what remains after winning.', lesson: 'If victory requires losing what matters most, is it still victory?' },
    it: { keywords: ['conflitto', 'vittoria', 'costo', 'discussione', 'interesse personale', 'vittoria vuota'], dailyU: 'Non danneggiare un rapporto soltanto per vincere. Convincere non significa risolvere: valuta se questa battaglia conta.', dailyR: 'Interrompi uno scontro inutile, chiedi scusa o lascia una lotta estenuante. Rinunciare a vincere permette di chiudere.', upright: 'Il Cinque di Spade diritto rappresenta conflitto, lotta di potere e vittoria costosa. Vincere fuori puo costare fiducia, collaborazione o pace.', reversed: 'Rovesciato, indica riconciliazione, rimorso, conseguenze o ostilita ancora nascosta. Finire la guerra richiede responsabilita.', intro: 'Il vincitore raccoglie le spade mentre gli altri si allontanano, mostrando cio che resta dopo la vittoria.', lesson: 'Se per vincere perdi cio che conta di piu, e ancora una vittoria?' },
  },
  {
    id: 'six-of-swords', number: 6, name_cn: '宝剑六', name_en: 'Six of Swords', name_it: 'Sei di Spade', suit: 'swords',
    zh: { keywords: ['过渡', '离开困境', '迁移', '恢复', '前行', '接受帮助'], dailyU: '今天适合离开混乱，向更平静的方向移动。过程未必轻松，但你已经不必留在原地。', dailyR: '今天要留意被旧问题拉回，或拒绝必要的改变。确认哪些包袱需要放下，哪些经验值得带走。', upright: '宝剑六正位代表过渡、迁移与逐渐离开困难。你可能仍带着悲伤，但环境和视角正在朝更平静的水域移动。', reversed: '宝剑六逆位代表转变受阻、旧问题反复、行程延迟，或内在尚未真正离开。换地点不一定等于完成疗愈。', intro: '宝剑六中的船载着人物穿过水面，说明恢复常常是一段缓慢而安静的迁移。', lesson: '它提醒你接受帮助，带走智慧，并允许自己一步步离开风暴。' },
    en: { keywords: ['transition', 'leaving difficulty', 'travel', 'recovery', 'moving on', 'accepting help'], dailyU: 'Move away from confusion toward calmer ground. The passage may be difficult, but you need not remain where you were.', dailyR: 'Watch for old issues pulling you back or resistance to necessary change. Decide what to release and what wisdom to carry.', upright: 'The Six of Swords upright represents transition, relocation, and gradual departure from difficulty. Sorrow may remain while conditions move toward calmer water.', reversed: 'Reversed, it represents blocked transition, recurring problems, delay, or an inner self that has not left. Changing place alone does not heal.', intro: 'A boat carries figures across water, showing recovery as a quiet and gradual passage.', lesson: 'Accept help, carry wisdom, and allow yourself to leave the storm step by step.' },
    it: { keywords: ['transizione', 'uscita dalla difficolta', 'viaggio', 'recupero', 'andare avanti', 'accettare aiuto'], dailyU: 'Allontanati dalla confusione verso acque piu calme. Il passaggio puo essere difficile, ma non devi restare dov’eri.', dailyR: 'Attenzione ai vecchi problemi che ti richiamano o alla resistenza al cambiamento. Decidi cosa lasciare e quale saggezza portare.', upright: 'Il Sei di Spade diritto rappresenta transizione, spostamento e uscita graduale dalla difficolta. Il dolore puo restare mentre la situazione diventa piu calma.', reversed: 'Rovesciato, indica transizione bloccata, problemi ricorrenti, ritardi o un’interiorita che non e ancora partita. Cambiare luogo non basta a guarire.', intro: 'Una barca trasporta figure sull’acqua, mostrando la guarigione come passaggio quieto e graduale.', lesson: 'Accetta aiuto, porta con te la saggezza e lascia la tempesta un passo alla volta.' },
  },
  {
    id: 'seven-of-swords', number: 7, name_cn: '宝剑七', name_en: 'Seven of Swords', name_it: 'Sette di Spade', suit: 'swords',
    zh: { keywords: ['策略', '隐瞒', '独立行动', '欺骗', '机智', '逃避责任'], dailyU: '今天适合谨慎规划、保护隐私，但不要用聪明掩盖不诚实。策略需要边界，也需要承担后果。', dailyR: '今天隐藏的信息可能暴露，或你终于愿意坦白。停止自我欺骗，能让复杂局面重新变简单。', upright: '宝剑七正位代表策略、秘密行动、绕开规则或欺骗。你可能需要独立思考，但也要确认自己的方法是否违背信任。', reversed: '宝剑七逆位代表真相揭露、认错、计划失败或更深的自我欺骗。聪明如果只用来逃避，最终会困住自己。', intro: '宝剑七中的人物带走刀剑并回头张望，是谋略与不安同时存在的画面。', lesson: '它提醒你：策略可以保护目标，但没有诚信的策略无法建立长久成果。' },
    en: { keywords: ['strategy', 'secrecy', 'independent action', 'deception', 'wit', 'avoiding responsibility'], dailyU: 'Plan carefully and protect privacy, but do not use intelligence to hide dishonesty. Strategy still carries consequences.', dailyR: 'Hidden information may surface, or you may finally speak honestly. Ending self-deception simplifies the situation.', upright: 'The Seven of Swords upright represents strategy, secrecy, bypassing rules, or deception. Independent thinking is useful, but methods may violate trust.', reversed: 'Reversed, it represents exposure, confession, failed plans, or deeper self-deception. Clever avoidance eventually becomes a trap.', intro: 'A figure carries swords away while looking back, combining strategy with unease.', lesson: 'Strategy can protect a goal, but strategy without integrity cannot build lasting results.' },
    it: { keywords: ['strategia', 'segretezza', 'azione indipendente', 'inganno', 'astuzia', 'fuga dalla responsabilita'], dailyU: 'Pianifica con prudenza e proteggi la privacy, ma non usare l’intelligenza per nascondere disonesta. Ogni strategia ha conseguenze.', dailyR: 'Informazioni nascoste possono emergere, oppure puoi finalmente essere sincera o sincero. Smettere di ingannarti semplifica la situazione.', upright: 'Il Sette di Spade diritto rappresenta strategia, segretezza, aggiramento delle regole o inganno. Pensare in autonomia aiuta, ma i metodi possono tradire la fiducia.', reversed: 'Rovesciato, indica rivelazione, confessione, piano fallito o autoinganno piu profondo. L’evitamento astuto diventa una trappola.', intro: 'Una figura porta via le spade guardandosi indietro, unendo strategia e inquietudine.', lesson: 'La strategia puo proteggere un obiettivo, ma senza integrita non costruisce risultati duraturi.' },
  },
  {
    id: 'eight-of-swords', number: 8, name_cn: '宝剑八', name_en: 'Eight of Swords', name_it: 'Otto di Spade', suit: 'swords',
    zh: { keywords: ['受限', '无力感', '自我束缚', '恐惧', '思维牢笼', '新视角'], dailyU: '今天可能觉得选择很少，但限制未必像想象中牢固。先移动一个小步骤，你会看见新的出口。', dailyR: '今天适合挣脱自我设限、求助或重新拿回选择权。你开始发现，眼罩和绳索并非无法解开。', upright: '宝剑八正位代表受困、无力感与由恐惧构成的思维牢笼。现实确有困难，但你对困难的解释可能进一步缩小了选择。', reversed: '宝剑八逆位代表释放、自我赋权与看见出口，也可能表示恐惧加剧。改变从承认自己仍有一点行动空间开始。', intro: '被蒙眼束缚的人站在宝剑之间，绳索并不完全牢固，暗示限制同时来自环境和内在信念。', lesson: '它提醒你：不必一次逃出全部困境，先找回一个可以由自己决定的动作。' },
    en: { keywords: ['restriction', 'powerlessness', 'self-limitation', 'fear', 'mental prison', 'new perspective'], dailyU: 'Choices may seem scarce, but the limits may not be absolute. Move one small step and another exit becomes visible.', dailyR: 'Break a self-imposed limit, ask for help, or reclaim choice. The blindfold and bonds can be loosened.', upright: 'The Eight of Swords upright represents feeling trapped, powerless, and confined by fear. Real difficulty exists, but your interpretation may shrink choice further.', reversed: 'Reversed, it represents release, empowerment, and seeing an exit, or fear becoming intense. Change begins by finding one available action.', intro: 'A bound and blindfolded person stands among swords, yet the bonds are not absolute; limitation comes from both circumstance and belief.', lesson: 'You need not escape everything at once. Reclaim one action that remains yours to choose.' },
    it: { keywords: ['limitazione', 'impotenza', 'auto-limitazione', 'paura', 'prigione mentale', 'nuova prospettiva'], dailyU: 'Le scelte possono sembrare poche, ma i limiti non sono assoluti. Muovi un piccolo passo e apparira un’altra uscita.', dailyR: 'Rompi un limite autoimposto, chiedi aiuto o riprendi la scelta. Benda e legami possono essere sciolti.', upright: 'L’Otto di Spade diritto rappresenta sentirsi intrappolati, impotenti e confinati dalla paura. La difficolta e reale, ma l’interpretazione puo ridurre ancora le scelte.', reversed: 'Rovesciato, indica liberazione, potere personale e uscita visibile, oppure paura crescente. Il cambiamento inizia trovando un’azione possibile.', intro: 'Una persona bendata e legata sta tra le spade, ma i legami non sono assoluti: il limite nasce sia dalla situazione sia dalle convinzioni.', lesson: 'Non devi uscire da tutto in una volta. Riprendi una sola azione che puoi ancora scegliere.' },
  },
  {
    id: 'nine-of-swords', number: 9, name_cn: '宝剑九', name_en: 'Nine of Swords', name_it: 'Nove di Spade', suit: 'swords',
    zh: { keywords: ['焦虑', '失眠', '内疚', '噩梦', '过度思考', '心理压力'], dailyU: '今天要留意焦虑和过度思考。脑中的最坏情境不等于现实，和可信任的人说出来会减轻重量。', dailyR: '今天可能开始走出焦虑，也可能把痛苦藏得更深。不要独自承受，必要时主动寻求专业支持。', upright: '宝剑九正位代表焦虑、失眠、内疚与被思想反复折磨。痛苦是真实的，但恐惧可能把尚未发生的结果放大。', reversed: '宝剑九逆位代表恢复、愿意求助，或焦虑进一步内化。你需要停止把所有问题留在夜里独自处理。', intro: '人物从床上惊醒，墙上悬着九把剑，描绘思想在黑夜中失去边界的状态。', lesson: '它提醒你把恐惧带到光下：事实、支持与休息能让脑中的剑慢慢放下。' },
    en: { keywords: ['anxiety', 'insomnia', 'guilt', 'nightmares', 'overthinking', 'mental stress'], dailyU: 'Notice anxiety and overthinking. The worst scenario in your mind is not automatically reality; share the weight.', dailyR: 'You may begin recovering or hide pain more deeply. Do not carry it alone; seek professional support when needed.', upright: 'The Nine of Swords upright represents anxiety, sleeplessness, guilt, and repetitive mental torment. Pain is real, while fear can magnify outcomes that have not happened.', reversed: 'Reversed, it represents recovery and asking for help, or anxiety turning further inward. Stop handling every problem alone at night.', intro: 'A figure wakes in bed beneath nine swords, showing thought losing boundaries in darkness.', lesson: 'Bring fear into the light. Facts, support, and rest can lower the swords in the mind.' },
    it: { keywords: ['ansia', 'insonnia', 'colpa', 'incubi', 'pensiero eccessivo', 'stress mentale'], dailyU: 'Osserva ansia e pensieri ripetitivi. Lo scenario peggiore nella mente non e automaticamente realta: condividi il peso.', dailyR: 'Puoi iniziare a recuperare oppure nascondere il dolore piu profondamente. Non portarlo da sola o da solo; cerca aiuto professionale se serve.', upright: 'Il Nove di Spade diritto rappresenta ansia, insonnia, colpa e tormento mentale ripetitivo. Il dolore e reale, ma la paura amplifica esiti non ancora accaduti.', reversed: 'Rovesciato, indica recupero e richiesta d’aiuto, oppure ansia ancora piu interiorizzata. Non affrontare ogni problema da sola o da solo nella notte.', intro: 'Una figura si sveglia nel letto sotto nove spade, mostrando il pensiero che perde confini nel buio.', lesson: 'Porta la paura alla luce. Fatti, sostegno e riposo possono abbassare le spade della mente.' },
  },
  {
    id: 'ten-of-swords', number: 10, name_cn: '宝剑十', name_en: 'Ten of Swords', name_it: 'Dieci di Spade', suit: 'swords',
    zh: { keywords: ['结束', '崩溃', '背叛', '触底', '接受', '黎明', '重新开始'], dailyU: '今天可能确认某件事已经走到尽头。结束令人痛苦，但最黑暗的时刻之后，新的光也正在出现。', dailyR: '今天适合从低谷恢复，但别否认仍需处理的伤口。停止拖延终点，才能真正重新开始。', upright: '宝剑十正位代表痛苦的结束、触底、背叛或某种无法再维持的状态。结局已经清楚，继续抵抗只会延长消耗。', reversed: '宝剑十逆位代表幸存、恢复、拒绝结束，或旧痛反复。你已经开始起身，但需要真正完成清理。', intro: '十把剑标志风元素周期的极限，远方的黎明同时说明最坏阶段不会永远持续。', lesson: '它的核心信息是：承认结束不是认输，而是停止让已经发生的事继续伤害未来。' },
    en: { keywords: ['ending', 'collapse', 'betrayal', 'rock bottom', 'acceptance', 'dawn', 'new beginning'], dailyU: 'Something may clearly reach its end. The ending hurts, but new light follows the darkest point.', dailyR: 'Recovery can begin, but wounds still need care. Stop postponing the ending so a new start can become real.', upright: 'The Ten of Swords upright represents painful ending, rock bottom, betrayal, or a condition that cannot continue. Resistance now may only extend exhaustion.', reversed: 'Reversed, it represents survival, recovery, refusal to end, or recurring pain. You are rising, but the cleanup must be completed.', intro: 'Ten swords mark the limit of the Air cycle, while dawn shows that the worst phase cannot last forever.', lesson: 'Accepting an ending is not defeat; it stops what happened from continuing to injure the future.' },
    it: { keywords: ['fine', 'crollo', 'tradimento', 'fondo', 'accettazione', 'alba', 'nuovo inizio'], dailyU: 'Qualcosa puo arrivare chiaramente alla fine. La conclusione fa male, ma dopo il punto piu buio arriva una nuova luce.', dailyR: 'Il recupero puo iniziare, ma le ferite richiedono cura. Non rimandare la fine se vuoi rendere reale un nuovo inizio.', upright: 'Il Dieci di Spade diritto rappresenta fine dolorosa, fondo, tradimento o una condizione che non puo continuare. Resistere puo soltanto prolungare l’esaurimento.', reversed: 'Rovesciato, indica sopravvivenza, recupero, rifiuto della fine o dolore ricorrente. Ti stai rialzando, ma la pulizia deve essere completata.', intro: 'Dieci spade segnano il limite del ciclo dell’Aria, mentre l’alba mostra che la fase peggiore non dura per sempre.', lesson: 'Accettare una fine non e sconfitta: impedisce a cio che e accaduto di continuare a ferire il futuro.' },
  },
  {
    id: 'page-of-swords', number: 11, name_cn: '宝剑侍从', name_en: 'Page of Swords', name_it: 'Fante di Spade', suit: 'swords',
    zh: { keywords: ['好奇', '观察', '新消息', '学习', '警觉', '表达'], dailyU: '今天适合学习、提问和观察细节。保持好奇，但不要急着把未经确认的信息传播出去。', dailyR: '今天要小心流言、口无遮拦或过度监视。聪明不等于知道全部，先听懂再回应。', upright: '宝剑侍从正位代表敏锐好奇、学习欲、新消息与快速观察。你正在建立表达和辨别信息的能力。', reversed: '宝剑侍从逆位代表流言、言语冲动、信息误用或计划多行动少。警觉过度也会变成猜疑。', intro: '宝剑侍从是刚学会使用思想与语言的风，反应迅速，也仍需要经验校准。', lesson: '它提醒你保持提问，同时让事实、责任和倾听跟上聪明。' },
    en: { keywords: ['curiosity', 'observation', 'news', 'learning', 'alertness', 'expression'], dailyU: 'Learn, ask, and observe details. Stay curious without spreading unverified information.', dailyR: 'Watch for gossip, reckless speech, or surveillance. Intelligence is not complete knowledge; listen first.', upright: 'The Page of Swords upright represents sharp curiosity, learning, news, and quick observation. You are developing expression and discernment.', reversed: 'Reversed, it represents gossip, impulsive speech, misuse of information, or plans without action. Alertness can become suspicion.', intro: 'The Page of Swords is Air learning to use thought and language: quick, alert, and still in need of experience.', lesson: 'Keep questioning while allowing facts, responsibility, and listening to keep pace with intelligence.' },
    it: { keywords: ['curiosita', 'osservazione', 'notizie', 'studio', 'attenzione', 'espressione'], dailyU: 'Studia, fai domande e osserva i dettagli. Resta curiosa o curioso senza diffondere informazioni non verificate.', dailyR: 'Attenzione a pettegolezzi, parole impulsive o controllo eccessivo. Intelligenza non significa sapere tutto: ascolta prima.', upright: 'Il Fante di Spade diritto rappresenta curiosita acuta, apprendimento, notizie e osservazione rapida. Stai sviluppando espressione e discernimento.', reversed: 'Rovesciato, indica pettegolezzo, parole impulsive, uso scorretto delle informazioni o progetti senza azione. L’attenzione puo diventare sospetto.', intro: 'Il Fante di Spade e l’Aria che impara a usare pensiero e linguaggio: rapido, vigile e ancora bisognoso di esperienza.', lesson: 'Continua a fare domande, lasciando che fatti, responsabilita e ascolto seguano l’intelligenza.' },
  },
  {
    id: 'knight-of-swords', number: 12, name_cn: '宝剑骑士', name_en: 'Knight of Swords', name_it: 'Cavaliere di Spade', suit: 'swords',
    zh: { keywords: ['速度', '野心', '直接', '争取', '行动', '言语锋利'], dailyU: '今天适合快速推进、直接表达和争取目标。速度是优势，但要确认方向和信息都准确。', dailyR: '今天要小心鲁莽、争辩或用强势语言碾过别人。先刹车，避免为一时正确付出长期代价。', upright: '宝剑骑士正位代表迅速行动、强烈目标感与直接沟通。你愿意为想法冲锋，但需要兼顾现实条件。', reversed: '宝剑骑士逆位代表鲁莽、攻击性、方向失控或只想证明自己正确。速度若没有判断，会制造新的混乱。', intro: '宝剑骑士让风元素高速前进，是思想变成行动时最直接而激烈的形态。', lesson: '它提醒你：勇敢表达，也给事实、后果和他人的声音留下空间。' },
    en: { keywords: ['speed', 'ambition', 'directness', 'pursuit', 'action', 'sharp speech'], dailyU: 'Move quickly, speak directly, and pursue the goal. Speed helps only when direction and information are sound.', dailyR: 'Watch for recklessness, argument, or forceful language. Slow down before a moment of being right creates a lasting cost.', upright: 'The Knight of Swords upright represents rapid action, strong purpose, and direct communication. You charge for an idea, but must include practical conditions.', reversed: 'Reversed, it represents recklessness, aggression, lost direction, or obsession with being right. Speed without judgment creates chaos.', intro: 'The Knight of Swords sends Air forward at full speed, thought becoming action in its most direct and intense form.', lesson: 'Speak bravely while leaving room for facts, consequences, and other voices.' },
    it: { keywords: ['velocita', 'ambizione', 'franchezza', 'conquista', 'azione', 'parole taglienti'], dailyU: 'Avanza rapidamente, parla in modo diretto e persegui l’obiettivo. La velocita aiuta solo se direzione e informazioni sono solide.', dailyR: 'Attenzione a imprudenza, discussioni o linguaggio aggressivo. Rallenta prima che avere ragione per un attimo crei un costo duraturo.', upright: 'Il Cavaliere di Spade diritto rappresenta azione rapida, forte intenzione e comunicazione diretta. Combatti per un’idea, ma devi considerare la realta.', reversed: 'Rovesciato, indica imprudenza, aggressivita, direzione perduta o ossessione per avere ragione. La velocita senza giudizio crea caos.', intro: 'Il Cavaliere di Spade lancia l’Aria alla massima velocita: il pensiero diventa azione nella forma piu intensa.', lesson: 'Parla con coraggio lasciando spazio a fatti, conseguenze e altre voci.' },
  },
  {
    id: 'queen-of-swords', number: 13, name_cn: '宝剑皇后', name_en: 'Queen of Swords', name_it: 'Regina di Spade', suit: 'swords',
    zh: { keywords: ['独立', '清醒', '边界', '诚实', '洞察', '理性', '女性贵人'], dailyU: '今天适合清晰设立边界、独立判断。诚实可以直接，但不必残酷。', dailyR: '今天要小心冷漠、尖锐或因旧伤拒绝所有靠近。保护自己时，也别切断真正的理解。', upright: '宝剑皇后正位代表清醒、独立、诚实与成熟边界。她能看穿复杂说辞，并以经验作出理性判断。', reversed: '宝剑皇后逆位代表苦涩、冷酷、过度批判或伤痛扭曲判断。锋利的边界可能变成拒绝连接的高墙。', intro: '宝剑皇后经历过风雨，因此她的清晰不是天真，而是由经验磨出的辨别力。', lesson: '她提醒你把真话说清，也让智慧保留同情和人性。' },
    en: { keywords: ['independence', 'clarity', 'boundaries', 'honesty', 'insight', 'reason', 'female benefactor'], dailyU: 'Set clear boundaries and judge independently. Honesty can be direct without becoming cruel.', dailyR: 'Watch for coldness, sharp criticism, or old pain rejecting every approach. Protection need not destroy understanding.', upright: 'The Queen of Swords upright represents clarity, independence, honesty, and mature boundaries. Experience helps her see through complicated claims.', reversed: 'Reversed, she represents bitterness, cruelty, excessive criticism, or pain distorting judgment. A boundary can become a wall.', intro: 'The Queen of Swords has weathered difficulty; her clarity is discernment sharpened by experience.', lesson: 'Speak truth clearly while allowing wisdom to retain compassion and humanity.' },
    it: { keywords: ['indipendenza', 'chiarezza', 'confini', 'onesta', 'intuizione', 'ragione', 'figura femminile favorevole'], dailyU: 'Stabilisci confini chiari e giudica in autonomia. L’onesta puo essere diretta senza diventare crudele.', dailyR: 'Attenzione a freddezza, critica tagliente o vecchie ferite che rifiutano ogni vicinanza. Proteggerti non deve eliminare la comprensione.', upright: 'La Regina di Spade diritta rappresenta chiarezza, indipendenza, onesta e confini maturi. L’esperienza le permette di vedere oltre discorsi complicati.', reversed: 'Rovesciata, indica amarezza, durezza, critica eccessiva o dolore che distorce il giudizio. Un confine puo diventare un muro.', intro: 'La Regina di Spade ha attraversato difficolta; la sua chiarezza e discernimento affilato dall’esperienza.', lesson: 'Di la verita con chiarezza, lasciando alla saggezza compassione e umanita.' },
  },
  {
    id: 'king-of-swords', number: 14, name_cn: '宝剑国王', name_en: 'King of Swords', name_it: 'Re di Spade', suit: 'swords',
    zh: { keywords: ['权威', '逻辑', '公正', '战略', '纪律', '判断', '男性贵人'], dailyU: '今天适合依据事实制定规则和策略。保持公正，别让个人情绪替代原则。', dailyR: '今天要小心滥用权威、僵化判断或用逻辑压制他人。聪明若缺少伦理，会变成控制。', upright: '宝剑国王正位代表理性权威、战略思考、公正判断与清晰规则。他能够在复杂信息中建立秩序并承担决策责任。', reversed: '宝剑国王逆位代表操控、冷酷、滥权、偏见或只用理论回避人性。权威失去伦理后会制造压迫。', intro: '宝剑国王是风元素成熟的治理者，把知识、语言和逻辑转化为制度与决策。', lesson: '他提醒你：最强的判断不仅准确，也透明、公正并愿意接受检验。' },
    en: { keywords: ['authority', 'logic', 'fairness', 'strategy', 'discipline', 'judgment', 'male benefactor'], dailyU: 'Build rules and strategy from facts. Remain fair and do not let personal emotion replace principle.', dailyR: 'Watch for abuse of authority, rigid judgment, or logic used to silence others. Intelligence without ethics becomes control.', upright: 'The King of Swords upright represents rational authority, strategy, fair judgment, and clear rules. He creates order from complexity and owns decisions.', reversed: 'Reversed, he represents manipulation, coldness, abuse of power, bias, or theory used to avoid humanity. Authority without ethics oppresses.', intro: 'The King of Swords is mature Air governing through knowledge, language, logic, and decision.', lesson: 'The strongest judgment is accurate, transparent, fair, and open to examination.' },
    it: { keywords: ['autorita', 'logica', 'equita', 'strategia', 'disciplina', 'giudizio', 'figura maschile favorevole'], dailyU: 'Costruisci regole e strategia sui fatti. Resta equa o equo e non lasciare che l’emozione personale sostituisca il principio.', dailyR: 'Attenzione ad abuso di autorita, giudizio rigido o logica usata per zittire. L’intelligenza senza etica diventa controllo.', upright: 'Il Re di Spade diritto rappresenta autorita razionale, strategia, giudizio equo e regole chiare. Crea ordine nella complessita e si assume le decisioni.', reversed: 'Rovesciato, indica manipolazione, freddezza, abuso di potere, pregiudizio o teoria usata per evitare l’umanita. L’autorita senza etica opprime.', intro: 'Il Re di Spade e l’Aria matura che governa attraverso conoscenza, linguaggio, logica e decisione.', lesson: 'Il giudizio piu forte e accurato, trasparente, equo e disponibile a essere verificato.' },
  },
];

export const swordMeanings = swords.map(buildCard);

const pentacles = [
  { id: 'ace-of-pentacles', number: 1, name_cn: '星币首牌', name_en: 'Ace of Pentacles', name_it: 'Asso di Denari', suit: 'pentacles',
    zh: { keywords: ['机会', '金钱', '工作', '健康', '种子', '稳定'], dailyU: '今天适合接住一个现实机会，从小而具体的行动开始。', dailyR: '今天要小心错过机会、财务判断失误或只想收获却不愿播种。', upright: '星币首牌正位代表新的现实机会、资源、工作或健康基础。它是一颗可以长期生长的种子。', reversed: '星币首牌逆位代表机会延误、计划缺乏基础、财务损失或资源没有被正确使用。', intro: '星币首牌是土元素最初的礼物，把可能性放进可触摸的现实。', lesson: '它提醒你珍惜起点，用稳定行动让机会真正生根。' },
    en: { keywords: ['opportunity', 'money', 'work', 'health', 'seed', 'stability'], dailyU: 'Receive a practical opportunity and begin with one concrete action.', dailyR: 'Watch for missed opportunity, poor financial judgment, or expecting harvest without planting.', upright: 'The Ace of Pentacles upright represents a new practical opportunity, resource, job, or foundation for health. It is a seed with long-term potential.', reversed: 'Reversed, it represents delay, weak foundations, financial loss, or resources used poorly.', intro: 'The Ace of Pentacles is Earth’s first gift, placing possibility into tangible reality.', lesson: 'Value the beginning and let steady action give the opportunity roots.' },
    it: { keywords: ['opportunita', 'denaro', 'lavoro', 'salute', 'seme', 'stabilita'], dailyU: 'Accogli un’opportunita concreta e inizia con una piccola azione reale.', dailyR: 'Attenzione a occasioni perse, giudizi finanziari sbagliati o raccolto atteso senza semina.', upright: 'L’Asso di Denari diritto rappresenta nuova opportunita concreta, risorsa, lavoro o base di salute. E un seme dal potenziale duraturo.', reversed: 'Rovesciato, indica ritardo, basi fragili, perdita economica o risorse usate male.', intro: 'L’Asso di Denari e il primo dono della Terra, che porta la possibilita nella realta tangibile.', lesson: 'Dai valore all’inizio e lascia che l’azione costante metta radici.' } },
  { id: 'two-of-pentacles', number: 2, name_cn: '星币二', name_en: 'Two of Pentacles', name_it: 'Due di Denari', suit: 'pentacles',
    zh: { keywords: ['平衡', '多任务', '适应', '节奏', '财务安排', '灵活'], dailyU: '今天适合灵活安排时间与金钱，先处理最重要的事项。', dailyR: '今天要小心任务过载、预算混乱或为了兼顾一切而失去重点。', upright: '星币二正位代表在变化中保持平衡、灵活管理多项责任。', reversed: '星币二逆位代表过载、失衡、时间或财务管理失控。', intro: '人物让两枚星币循环移动，说明稳定有时来自持续调整。', lesson: '真正的平衡不是一动不动，而是知道何时取舍。' },
    en: { keywords: ['balance', 'multitasking', 'adaptation', 'rhythm', 'budgeting', 'flexibility'], dailyU: 'Arrange time and money flexibly, beginning with what matters most.', dailyR: 'Watch for overload, budget confusion, or losing priorities while trying to do everything.', upright: 'The Two of Pentacles upright represents balance through change and flexible management of responsibilities.', reversed: 'Reversed, it represents overload and loss of control over time, money, or priorities.', intro: 'The moving coins show that stability sometimes comes from continuous adjustment.', lesson: 'Balance is not stillness; it is knowing when to choose.' },
    it: { keywords: ['equilibrio', 'multitasking', 'adattamento', 'ritmo', 'bilancio', 'flessibilita'], dailyU: 'Organizza tempo e denaro con flessibilita, iniziando da cio che conta.', dailyR: 'Attenzione a sovraccarico, confusione economica o perdita delle priorita.', upright: 'Il Due di Denari diritto rappresenta equilibrio nel cambiamento e gestione flessibile delle responsabilita.', reversed: 'Rovesciato, indica sovraccarico e perdita di controllo su tempo, denaro o priorita.', intro: 'Le monete in movimento mostrano che la stabilita nasce talvolta da un continuo adattamento.', lesson: 'Equilibrio non significa immobilita, ma sapere quando scegliere.' } },
  { id: 'three-of-pentacles', number: 3, name_cn: '星币三', name_en: 'Three of Pentacles', name_it: 'Tre di Denari', suit: 'pentacles',
    zh: { keywords: ['合作', '技能', '团队', '学习', '认可', '建设'], dailyU: '今天适合协作、请教专业意见并认真打磨技能。', dailyR: '今天要小心团队沟通不良、质量不足或各做各的。', upright: '星币三正位代表专业合作、技能成长与共同建设成果。', reversed: '星币三逆位代表配合失效、标准不一或能力没有得到认真培养。', intro: '工匠与伙伴共同审视建筑，说明好成果来自能力与协作。', lesson: '尊重专业，也让每个人清楚自己在共同目标中的位置。' },
    en: { keywords: ['cooperation', 'skill', 'teamwork', 'learning', 'recognition', 'building'], dailyU: 'Collaborate, seek expert input, and refine your craft.', dailyR: 'Watch for poor teamwork, weak quality, or everyone working in isolation.', upright: 'The Three of Pentacles upright represents skilled cooperation, learning, and building a shared result.', reversed: 'Reversed, it represents failed coordination, inconsistent standards, or neglected skill.', intro: 'Craftspeople review a structure together, showing that quality combines ability and cooperation.', lesson: 'Respect expertise and clarify each person’s role in the shared goal.' },
    it: { keywords: ['collaborazione', 'abilita', 'squadra', 'studio', 'riconoscimento', 'costruzione'], dailyU: 'Collabora, chiedi pareri esperti e perfeziona il tuo mestiere.', dailyR: 'Attenzione a cattiva collaborazione, qualita debole o lavoro isolato.', upright: 'Il Tre di Denari diritto rappresenta cooperazione competente, apprendimento e costruzione comune.', reversed: 'Rovesciato, indica coordinamento fallito, standard incoerenti o abilita trascurate.', intro: 'Artigiani osservano insieme una struttura: la qualita unisce capacita e collaborazione.', lesson: 'Rispetta la competenza e chiarisci il ruolo di ciascuno.' } },
  { id: 'four-of-pentacles', number: 4, name_cn: '星币四', name_en: 'Four of Pentacles', name_it: 'Quattro di Denari', suit: 'pentacles',
    zh: { keywords: ['保守', '安全感', '控制', '储蓄', '占有', '边界'], dailyU: '今天适合保护资源、检查预算和建立现实边界。', dailyR: '今天要小心抓得太紧，或因恐惧失去而无法流动和分享。', upright: '星币四正位代表守住资源、追求安全与控制风险。', reversed: '星币四逆位代表放松控制、财务不稳，或占有欲造成停滞。', intro: '人物紧抱星币，显示安全感与封闭只隔着很小距离。', lesson: '保存资源有价值，但真正的稳定也需要适度流动。' },
    en: { keywords: ['conservation', 'security', 'control', 'saving', 'possession', 'boundaries'], dailyU: 'Protect resources, review the budget, and establish practical boundaries.', dailyR: 'Watch for holding too tightly or fear preventing circulation and sharing.', upright: 'The Four of Pentacles upright represents conserving resources, seeking security, and controlling risk.', reversed: 'Reversed, it represents releasing control, financial instability, or possession creating stagnation.', intro: 'The figure grips the coins, showing the narrow distance between security and closure.', lesson: 'Saving matters, but lasting stability also needs healthy circulation.' },
    it: { keywords: ['conservazione', 'sicurezza', 'controllo', 'risparmio', 'possesso', 'confini'], dailyU: 'Proteggi le risorse, controlla il bilancio e stabilisci confini concreti.', dailyR: 'Attenzione a trattenere troppo o a impedire scambio e condivisione per paura.', upright: 'Il Quattro di Denari diritto rappresenta conservazione, sicurezza e controllo del rischio.', reversed: 'Rovesciato, indica rilascio del controllo, instabilita economica o possesso che blocca.', intro: 'La figura stringe le monete, mostrando quanto sicurezza e chiusura siano vicine.', lesson: 'Risparmiare conta, ma la stabilita ha bisogno anche di circolazione sana.' } },
  { id: 'five-of-pentacles', number: 5, name_cn: '星币五', name_en: 'Five of Pentacles', name_it: 'Cinque di Denari', suit: 'pentacles',
    zh: { keywords: ['匮乏', '困难', '孤立', '经济压力', '求助', '恢复'], dailyU: '今天可能感到资源不足或被排除。不要独自受冻，帮助也许比你想象中更近。', dailyR: '今天适合走出困境、接受支持，并重新建立现实安全感。', upright: '星币五正位代表经济、健康或归属上的困难与匮乏感。', reversed: '星币五逆位代表恢复、援助出现，或最艰难阶段逐渐过去。', intro: '风雪中的人物经过亮着灯的窗，说明困境真实，支持也仍然存在。', lesson: '它提醒你求助不是失败，资源和连接能共同帮助人走出寒冬。' },
    en: { keywords: ['scarcity', 'hardship', 'isolation', 'financial stress', 'asking for help', 'recovery'], dailyU: 'Resources may feel scarce or you may feel excluded. Do not suffer alone; help may be nearby.', dailyR: 'Accept support and rebuild practical security as conditions improve.', upright: 'The Five of Pentacles upright represents financial, physical, or social hardship and scarcity.', reversed: 'Reversed, it represents recovery, available support, or the hardest phase passing.', intro: 'Figures in snow pass a lit window: hardship is real, and support still exists.', lesson: 'Asking for help is not failure; resources and connection can end the winter.' },
    it: { keywords: ['scarsita', 'difficolta', 'isolamento', 'pressione economica', 'chiedere aiuto', 'recupero'], dailyU: 'Le risorse possono sembrare scarse o puoi sentirti esclusa o escluso. Non soffrire da sola o solo: l’aiuto puo essere vicino.', dailyR: 'Accetta sostegno e ricostruisci sicurezza concreta mentre la situazione migliora.', upright: 'Il Cinque di Denari diritto rappresenta difficolta economica, fisica o sociale e senso di scarsita.', reversed: 'Rovesciato, indica recupero, sostegno disponibile o la fase peggiore che passa.', intro: 'Figure nella neve passano davanti a una finestra illuminata: la difficolta e reale e l’aiuto esiste.', lesson: 'Chiedere aiuto non e fallire; risorse e connessione possono terminare l’inverno.' } },
  { id: 'six-of-pentacles', number: 6, name_cn: '星币六', name_en: 'Six of Pentacles', name_it: 'Sei di Denari', suit: 'pentacles',
    zh: { keywords: ['给予', '接受', '公平', '援助', '资源分配', '权力'], dailyU: '今天适合给予力所能及的帮助，也坦然接受需要的支持。', dailyR: '今天要小心附带条件的帮助、债务失衡或用资源控制别人。', upright: '星币六正位代表资源分享、援助与相对公平的交换。', reversed: '星币六逆位代表不平等、单向付出、债务或带有控制的慷慨。', intro: '天平与施予的动作提醒人关注谁掌握资源、谁拥有选择权。', lesson: '真正的慷慨保留尊严，也让给予和接受都能自由发生。' },
    en: { keywords: ['giving', 'receiving', 'fairness', 'aid', 'resource distribution', 'power'], dailyU: 'Offer help within your means and receive needed support without shame.', dailyR: 'Watch for conditional help, unequal debt, or resources used to control.', upright: 'The Six of Pentacles upright represents sharing resources, aid, and relatively fair exchange.', reversed: 'Reversed, it represents inequality, one-way giving, debt, or generosity used as control.', intro: 'The scales and act of giving ask who holds resources and who retains choice.', lesson: 'True generosity preserves dignity and lets giving and receiving remain free.' },
    it: { keywords: ['dare', 'ricevere', 'equita', 'aiuto', 'distribuzione delle risorse', 'potere'], dailyU: 'Offri aiuto entro le tue possibilita e ricevi sostegno senza vergogna.', dailyR: 'Attenzione ad aiuto condizionato, debiti diseguali o risorse usate per controllare.', upright: 'Il Sei di Denari diritto rappresenta condivisione, aiuto e scambio relativamente equo.', reversed: 'Rovesciato, indica disuguaglianza, dono unilaterale, debito o generosita usata come controllo.', intro: 'La bilancia e il gesto del dono chiedono chi possiede risorse e chi conserva scelta.', lesson: 'La vera generosita preserva dignita e liberta nel dare e ricevere.' } },
  { id: 'seven-of-pentacles', number: 7, name_cn: '星币七', name_en: 'Seven of Pentacles', name_it: 'Sette di Denari', suit: 'pentacles',
    zh: { keywords: ['等待', '评估', '耐心', '投资', '长期成果', '调整'], dailyU: '今天适合检查长期投入和阶段成果。耐心等待，同时调整无效的方法。', dailyR: '今天要小心急于回报、投入方向错误或因进展慢而放弃。', upright: '星币七正位代表耐心培育、评估投资与等待成果成熟。', reversed: '星币七逆位代表回报不足、缺乏耐心或继续投入不值得的方向。', intro: '园丁看着作物，说明成长需要时间，也需要阶段性检查。', lesson: '坚持不是盲目等待，而是根据真实进展决定继续、调整或停止。' },
    en: { keywords: ['waiting', 'assessment', 'patience', 'investment', 'long-term results', 'adjustment'], dailyU: 'Review long-term effort and current results. Wait patiently while changing ineffective methods.', dailyR: 'Watch for impatience, poor investment, or abandoning work only because growth is slow.', upright: 'The Seven of Pentacles upright represents patient cultivation, reviewing investment, and waiting for maturity.', reversed: 'Reversed, it represents weak return, impatience, or continued investment in the wrong direction.', intro: 'A gardener studies the crop, showing that growth needs both time and review.', lesson: 'Persistence means using evidence to continue, adjust, or stop, not waiting blindly.' },
    it: { keywords: ['attesa', 'valutazione', 'pazienza', 'investimento', 'risultati a lungo termine', 'correzione'], dailyU: 'Rivedi l’impegno di lungo periodo e i risultati. Attendi con pazienza correggendo i metodi inefficaci.', dailyR: 'Attenzione a impazienza, investimento sbagliato o abbandono soltanto perche la crescita e lenta.', upright: 'Il Sette di Denari diritto rappresenta coltivazione paziente, valutazione dell’investimento e attesa della maturita.', reversed: 'Rovesciato, indica scarso rendimento, impazienza o investimento continuato nella direzione sbagliata.', intro: 'Un giardiniere osserva il raccolto: crescere richiede tempo e verifica.', lesson: 'Perseverare significa decidere con prove se continuare, correggere o fermarsi.' } },
  { id: 'eight-of-pentacles', number: 8, name_cn: '星币八', name_en: 'Eight of Pentacles', name_it: 'Otto di Denari', suit: 'pentacles',
    zh: { keywords: ['勤奋', '练习', '专注', '工艺', '精进', '重复'], dailyU: '今天适合专注练习、完成细节和提高专业能力。', dailyR: '今天要小心敷衍、完美主义或机械重复却没有真正成长。', upright: '星币八正位代表勤奋、专注练习与通过重复建立专业能力。', reversed: '星币八逆位代表质量下降、缺乏投入、工作成瘾或完美主义。', intro: '工匠反复雕刻星币，说明熟练来自耐心而具体的劳动。', lesson: '天赋打开门，持续练习才让能力真正可靠。' },
    en: { keywords: ['diligence', 'practice', 'focus', 'craft', 'mastery', 'repetition'], dailyU: 'Practice with focus, complete details, and improve professional skill.', dailyR: 'Watch for careless work, perfectionism, or repetition without real learning.', upright: 'The Eight of Pentacles upright represents diligence, focused practice, and skill built through repetition.', reversed: 'Reversed, it represents poor quality, low commitment, work addiction, or perfectionism.', intro: 'A craftsperson repeatedly shapes coins, showing mastery built through patient labor.', lesson: 'Talent opens the door; consistent practice makes ability dependable.' },
    it: { keywords: ['diligenza', 'pratica', 'concentrazione', 'mestiere', 'maestria', 'ripetizione'], dailyU: 'Esercitati con concentrazione, cura i dettagli e migliora la competenza.', dailyR: 'Attenzione a lavoro trascurato, perfezionismo o ripetizione senza apprendimento.', upright: 'L’Otto di Denari diritto rappresenta diligenza, pratica concentrata e abilita costruita con la ripetizione.', reversed: 'Rovesciato, indica bassa qualita, scarso impegno, dipendenza dal lavoro o perfezionismo.', intro: 'Un artigiano modella ripetutamente le monete, mostrando la maestria nata dal lavoro paziente.', lesson: 'Il talento apre la porta; la pratica costante rende affidabile la capacita.' } },
  { id: 'nine-of-pentacles', number: 9, name_cn: '星币九', name_en: 'Nine of Pentacles', name_it: 'Nove di Denari', suit: 'pentacles',
    zh: { keywords: ['独立', '丰盛', '自律', '享受成果', '品位', '安全'], dailyU: '今天适合享受靠自己建立的成果，也继续照顾身体与生活品质。', dailyR: '今天要小心表面精致、财务依赖或为了维持形象而过度消费。', upright: '星币九正位代表独立、物质稳定、自律与有能力享受成果。', reversed: '星币九逆位代表依赖、不安全、过度消费或成功外观下的空虚。', intro: '丰盛花园中的人物展示长期经营后获得的自由和从容。', lesson: '真正的富足不仅是拥有，也包括自主、节制和安心享受。' },
    en: { keywords: ['independence', 'abundance', 'discipline', 'enjoyment', 'refinement', 'security'], dailyU: 'Enjoy what you have built independently and continue caring for body and quality of life.', dailyR: 'Watch for polished appearances, financial dependence, or overspending to maintain an image.', upright: 'The Nine of Pentacles upright represents independence, material stability, discipline, and earned enjoyment.', reversed: 'Reversed, it represents dependence, insecurity, overspending, or emptiness beneath success.', intro: 'A figure in a rich garden shows freedom and ease created by long cultivation.', lesson: 'Abundance includes ownership, autonomy, moderation, and the ability to enjoy safely.' },
    it: { keywords: ['indipendenza', 'abbondanza', 'disciplina', 'godimento', 'raffinatezza', 'sicurezza'], dailyU: 'Goditi cio che hai costruito in autonomia e continua a curare corpo e qualita della vita.', dailyR: 'Attenzione a immagine raffinata, dipendenza economica o spese per mantenere un’apparenza.', upright: 'Il Nove di Denari diritto rappresenta indipendenza, stabilita materiale, disciplina e piacere meritato.', reversed: 'Rovesciato, indica dipendenza, insicurezza, spese eccessive o vuoto sotto il successo.', intro: 'Una figura in un giardino ricco mostra liberta e serenita create da una lunga coltivazione.', lesson: 'L’abbondanza comprende possesso, autonomia, misura e capacita di godere in sicurezza.' } },
  { id: 'ten-of-pentacles', number: 10, name_cn: '星币十', name_en: 'Ten of Pentacles', name_it: 'Dieci di Denari', suit: 'pentacles',
    zh: { keywords: ['传承', '家庭财富', '长期稳定', '家业', '根基', '遗产'], dailyU: '今天适合考虑长期保障、家庭资源和能够留下来的成果。', dailyR: '今天要小心家庭金钱冲突、短视决定或传统成为束缚。', upright: '星币十正位代表长期财富、家庭根基、传承与稳定体系。', reversed: '星币十逆位代表家族冲突、财务基础不稳、遗产问题或价值观断裂。', intro: '跨越世代的人物与星币展示个人成果如何进入家庭和长期结构。', lesson: '真正的传承不只留下财富，也留下健康的规则、关系与选择。' },
    en: { keywords: ['legacy', 'family wealth', 'long-term stability', 'estate', 'foundation', 'inheritance'], dailyU: 'Consider long-term security, family resources, and results that can endure.', dailyR: 'Watch for family money conflict, short-term decisions, or tradition becoming restrictive.', upright: 'The Ten of Pentacles upright represents lasting wealth, family foundation, legacy, and stable systems.', reversed: 'Reversed, it represents family conflict, weak finances, inheritance issues, or broken values.', intro: 'Several generations and ten coins show personal results entering family and lasting structure.', lesson: 'A healthy legacy leaves not only wealth, but sound rules, relationships, and choice.' },
    it: { keywords: ['eredita', 'ricchezza familiare', 'stabilita duratura', 'patrimonio', 'fondamenta', 'successione'], dailyU: 'Considera sicurezza di lungo periodo, risorse familiari e risultati capaci di durare.', dailyR: 'Attenzione a conflitti economici familiari, decisioni miopi o tradizioni restrittive.', upright: 'Il Dieci di Denari diritto rappresenta ricchezza duratura, fondamenta familiari, eredita e sistemi stabili.', reversed: 'Rovesciato, indica conflitto familiare, finanze fragili, problemi di successione o valori spezzati.', intro: 'Piu generazioni e dieci monete mostrano risultati personali inseriti in una struttura duratura.', lesson: 'Una buona eredita lascia non solo ricchezza, ma regole sane, relazioni e liberta di scelta.' } },
  { id: 'page-of-pentacles', number: 11, name_cn: '星币侍从', name_en: 'Page of Pentacles', name_it: 'Fante di Denari', suit: 'pentacles',
    zh: { keywords: ['学习', '新工作', '务实目标', '专注', '机会', '技能起点'], dailyU: '今天适合学习新技能、制定现实目标或认真处理一个小机会。', dailyR: '今天要小心拖延、缺乏专注或只有计划没有练习。', upright: '星币侍从正位代表务实学习、新工作机会与愿意从基础开始。', reversed: '星币侍从逆位代表懒散、缺乏计划、学习受阻或不切实际的目标。', intro: '星币侍从认真观察手中资源，是土元素谦逊而专注的学生。', lesson: '把好奇变成练习，把目标拆成今天能够完成的一步。' },
    en: { keywords: ['learning', 'new work', 'practical goal', 'focus', 'opportunity', 'beginning skill'], dailyU: 'Learn a skill, set a practical goal, or take a small opportunity seriously.', dailyR: 'Watch for procrastination, poor focus, or plans without practice.', upright: 'The Page of Pentacles upright represents practical learning, a new work opportunity, and willingness to begin with basics.', reversed: 'Reversed, it represents laziness, weak planning, blocked study, or unrealistic goals.', intro: 'The Page studies the resource in hand, a humble and focused student of Earth.', lesson: 'Turn curiosity into practice and break the goal into one step you can do today.' },
    it: { keywords: ['studio', 'nuovo lavoro', 'obiettivo pratico', 'concentrazione', 'opportunita', 'inizio di abilita'], dailyU: 'Impara una capacita, stabilisci un obiettivo concreto o prendi sul serio una piccola occasione.', dailyR: 'Attenzione a procrastinazione, scarsa concentrazione o piani senza pratica.', upright: 'Il Fante di Denari diritto rappresenta apprendimento pratico, nuova opportunita di lavoro e volonta di iniziare dalle basi.', reversed: 'Rovesciato, indica pigrizia, pianificazione debole, studio bloccato o obiettivi irrealistici.', intro: 'Il Fante osserva attentamente la risorsa che tiene, studente umile e concentrato della Terra.', lesson: 'Trasforma la curiosita in pratica e dividi l’obiettivo in un passo possibile oggi.' } },
  { id: 'knight-of-pentacles', number: 12, name_cn: '星币骑士', name_en: 'Knight of Pentacles', name_it: 'Cavaliere di Denari', suit: 'pentacles',
    zh: { keywords: ['可靠', '耐心', '责任', '规律', '稳步前进', '坚持'], dailyU: '今天适合按计划稳步推进。进展也许不快，但可靠的行动会累积结果。', dailyR: '今天要小心停滞、固执、过度工作或重复流程却忘记目标。', upright: '星币骑士正位代表可靠、耐心、责任与持续执行。', reversed: '星币骑士逆位代表僵化、懒惰、停滞或被工作和习惯困住。', intro: '这位骑士不追求速度，而用稳定节奏把承诺带到终点。', lesson: '持续比冲动更可靠，但规律也需要根据现实更新。' },
    en: { keywords: ['reliability', 'patience', 'responsibility', 'routine', 'steady progress', 'persistence'], dailyU: 'Follow the plan steadily. Progress may be slow, but dependable action accumulates results.', dailyR: 'Watch for stagnation, rigidity, overwork, or repeating a process after forgetting the goal.', upright: 'The Knight of Pentacles upright represents reliability, patience, responsibility, and consistent execution.', reversed: 'Reversed, it represents rigidity, laziness, stagnation, or being trapped by work and routine.', intro: 'This knight values no speed; a steady rhythm carries commitment to completion.', lesson: 'Consistency is more reliable than impulse, but routines must still adapt to reality.' },
    it: { keywords: ['affidabilita', 'pazienza', 'responsabilita', 'routine', 'progresso costante', 'perseveranza'], dailyU: 'Segui il piano con costanza. Il progresso puo essere lento, ma l’azione affidabile accumula risultati.', dailyR: 'Attenzione a stasi, rigidita, troppo lavoro o ripetizione del processo dimenticando l’obiettivo.', upright: 'Il Cavaliere di Denari diritto rappresenta affidabilita, pazienza, responsabilita ed esecuzione costante.', reversed: 'Rovesciato, indica rigidita, pigrizia, stasi o prigionia nel lavoro e nella routine.', intro: 'Questo cavaliere non cerca velocita; un ritmo stabile porta l’impegno fino alla fine.', lesson: 'La costanza e piu affidabile dell’impulso, ma la routine deve adattarsi alla realta.' } },
  { id: 'queen-of-pentacles', number: 13, name_cn: '星币皇后', name_en: 'Queen of Pentacles', name_it: 'Regina di Denari', suit: 'pentacles',
    zh: { keywords: ['滋养', '务实', '富足', '家庭', '身体', '女性贵人'], dailyU: '今天适合照顾身体、家庭和现实需要，把温柔落实成具体行动。', dailyR: '今天要小心过度照顾别人、忽略自己，或用物质填补不安全感。', upright: '星币皇后正位代表务实滋养、资源管理、身体智慧与稳定照顾。', reversed: '星币皇后逆位代表自我忽视、工作家庭失衡、物质焦虑或过度付出。', intro: '星币皇后让土元素具有温度，把资源转化为可以安顿生命的环境。', lesson: '照顾别人之前，也要让自己的身体、时间和资源得到尊重。' },
    en: { keywords: ['nurturing', 'practicality', 'abundance', 'home', 'body', 'female benefactor'], dailyU: 'Care for body, home, and practical needs. Turn kindness into concrete action.', dailyR: 'Watch for caring for others while neglecting yourself, or using possessions to fill insecurity.', upright: 'The Queen of Pentacles upright represents practical nurturing, resource management, body wisdom, and stable care.', reversed: 'Reversed, she represents self-neglect, imbalance between work and home, material anxiety, or overgiving.', intro: 'The Queen gives Earth warmth, turning resources into an environment where life can settle.', lesson: 'Before caring for others, respect your own body, time, and resources.' },
    it: { keywords: ['cura', 'praticita', 'abbondanza', 'casa', 'corpo', 'figura femminile favorevole'], dailyU: 'Cura corpo, casa e bisogni concreti. Trasforma la gentilezza in azione reale.', dailyR: 'Attenzione a curare gli altri trascurando te, o a usare i beni per riempire insicurezza.', upright: 'La Regina di Denari diritta rappresenta cura pratica, gestione delle risorse, saggezza del corpo e stabilita.', reversed: 'Rovesciata, indica trascuratezza di se, squilibrio tra lavoro e casa, ansia materiale o dono eccessivo.', intro: 'La Regina da calore alla Terra e trasforma risorse in un ambiente che accoglie la vita.', lesson: 'Prima di curare gli altri, rispetta il tuo corpo, il tuo tempo e le tue risorse.' } },
  { id: 'king-of-pentacles', number: 14, name_cn: '星币国王', name_en: 'King of Pentacles', name_it: 'Re di Denari', suit: 'pentacles',
    zh: { keywords: ['财富', '经营', '稳定', '成功', '责任', '男性贵人'], dailyU: '今天适合稳健管理资源、做长期决定，并为现实成果承担责任。', dailyR: '今天要小心贪婪、物质至上、控制资源或只看短期利益。', upright: '星币国王正位代表成熟经营、物质稳定、可靠领导与长期成功。', reversed: '星币国王逆位代表贪婪、僵化、财务操控或用财富定义全部价值。', intro: '星币国王是土元素成熟的管理者，知道如何让资源持续创造安全与成果。', lesson: '真正的富足不仅能积累财富，也能负责地使用、保护和分享财富。' },
    en: { keywords: ['wealth', 'management', 'stability', 'success', 'responsibility', 'male benefactor'], dailyU: 'Manage resources steadily, make long-term decisions, and take responsibility for results.', dailyR: 'Watch for greed, materialism, control through money, or short-term profit replacing values.', upright: 'The King of Pentacles upright represents mature management, material stability, reliable leadership, and lasting success.', reversed: 'Reversed, he represents greed, rigidity, financial control, or defining all value through wealth.', intro: 'The King is mature Earth, able to make resources create continuing security and results.', lesson: 'True abundance not only accumulates wealth; it uses, protects, and shares it responsibly.' },
    it: { keywords: ['ricchezza', 'gestione', 'stabilita', 'successo', 'responsabilita', 'figura maschile favorevole'], dailyU: 'Gestisci le risorse con stabilita, decidi sul lungo periodo e assumiti la responsabilita dei risultati.', dailyR: 'Attenzione ad avidita, materialismo, controllo economico o profitto breve che sostituisce i valori.', upright: 'Il Re di Denari diritto rappresenta gestione matura, stabilita materiale, leadership affidabile e successo duraturo.', reversed: 'Rovesciato, indica avidita, rigidita, controllo finanziario o valore definito solo dalla ricchezza.', intro: 'Il Re e la Terra matura, capace di trasformare risorse in sicurezza e risultati continui.', lesson: 'La vera abbondanza non accumula soltanto: usa, protegge e condivide la ricchezza responsabilmente.' } },
];

export const pentacleMeanings = pentacles.map(buildCard);
export const remainingMinorMeanings = [...swordMeanings, ...pentacleMeanings];
